x=int(input("enter an integer value:"))
y=int(input("enter an integer value:"))
b=(x+y*5)
a=(x+y*5*10/2)
print("x+y*5:",a)
print("x+y*5*10/2:",b)
#average of the marks
english=float(input("marks of english:"))
maths=float(input("marks of maths:"))
hindi=float(input("marks of hindi: "))
t=float(int(input("marks of t:")))
science=float(input("marks of science:"))
a=float(t+english+hindi+maths+science)
print(a)
print(int(a/5))
